### PR TITLE
Updating README file to comply with Docker.

### PR DESCRIPTION
**Pull request by jmcoimbra**
Also it got extra updates ;-)

### CODE REVIEW

**Comment by jmcoimbra** [comment]
@gvillalta99 this is a good way to complement what you deliver to our project. README is important.

**Comment by habner** [comment]
After `npm install`, you should run gulp with `npm run build`

**Comment by gvillalta99** [comment]
@jmcoimbra thank you for reminding me about the README!
By the way, the text is very clarifying!

**Comment by gvillalta99** [comment]
@habner I will change the README in a different PR and will include a few more steps and commands, then I review the project's build steps with you and we can improve the documentation.

**Pull request merged**
